theme: jekyll-theme-cayman
title: Estract, Transform and Load Streaming Weather Data
description: Based on the assignments from Big Data Specialization by University of California San Diego on Coursera
